version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install django
      - run: docker-compose build
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python manage.py test
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: docker-compose up -d
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
