name: Issue Created
on:
  issues:
    types: [opened]
jobs:
  display_message:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install jq -y
    - name: Get issue information
      id: get_issue
      run: echo "::set-output name=issue_creator::$(cat $GITHUB_EVENT_PATH | jq '.issue.user.login')"
    - name: Display message
      run: echo "Hello ${{steps.get_issue.outputs.issue_creator}} Thank you for generating an issue to this project! Please wait while we get back to you."
